INSERT INTO `GTUProjectManagement`.`Priority` (`name`, `degree`) VALUES ('greatest seniority', '20');
INSERT INTO `GTUProjectManagement`.`Priority` (`name`, `degree`) VALUES ('superiority', '30');
INSERT INTO `GTUProjectManagement`.`Priority` (`name`, `degree`) VALUES ('supremacy', '40');
INSERT INTO `GTUProjectManagement`.`Priority` (`name`, `degree`) VALUES ('transcendence', '50');
INSERT INTO `GTUProjectManagement`.`Priority` (`name`, `degree`) VALUES ('crash project', '60');
INSERT INTO `GTUProjectManagement`.`Priority` (`name`, `degree`) VALUES ('greatest importance', '70');
INSERT INTO `GTUProjectManagement`.`Priority` (`name`, `degree`) VALUES ('previousness', '80');

INSERT INTO `GTUProjectManagement`.`TaskClasses` (`name`, `Description`) VALUES ('Ice Box', 'It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.');
INSERT INTO `GTUProjectManagement`.`TaskClasses` (`name`, `Description`) VALUES ('Emergency', 'Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.');
INSERT INTO `GTUProjectManagement`.`TaskClasses` (`name`, `Description`) VALUES ('In Progress', 'Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of \"de Finibus Bonorum et Malorum\" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance.');
INSERT INTO `GTUProjectManagement`.`TaskClasses` (`name`, `Description`) VALUES ('Testing', 'The first line of Lorem Ipsum, \"Lorem ipsum dolor sit amet..\", comes from a line in section 1.10.32.');
INSERT INTO `GTUProjectManagement`.`TaskClasses` (`name`, `Description`) VALUES ('Complete', 'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested.');

INSERT INTO `GTUProjectManagement`.`Project` (`name`, `description`, `start_date`, `end_date`) VALUES ('Most Important', 'This is the first project of our company', '1000-01-01 00:00:00', '9999-12-31 23:59:59');
INSERT INTO `GTUProjectManagement`.`Project` (`name`, `description`, `start_date`, `end_date`) VALUES ('Road-to-Success Workshop', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', '2022-06-17 00:00:00', '2022-08-17 23:59:59');
INSERT INTO `GTUProjectManagement`.`Project` (`name`, `description`, `start_date`, `end_date`) VALUES ('Passion Chasers', 'Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ', '2022-06-17 00:00:00', '2022-08-17 23:59:59');
INSERT INTO `GTUProjectManagement`.`Project` (`name`, `description`, `start_date`, `end_date`) VALUES ('Commission Kings', 'It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ', '2022-06-17 00:00:00', '2022-08-17 23:59:59');
INSERT INTO `GTUProjectManagement`.`Project` (`name`, `description`, `start_date`, `end_date`) VALUES ('Coding Region', 'It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', '2022-06-17 00:00:00', '2022-08-17 23:59:59');
INSERT INTO `GTUProjectManagement`.`Project` (`name`, `description`, `start_date`, `end_date`) VALUES ('15 Five', 'Contrary to popular belief, Lorem Ipsum is not simply random text.', '2022-06-17 00:00:00', '2022-08-17 23:59:59');

INSERT INTO `GTUProjectManagement`.`User` (`first_name`, `last_name`, `email`, `password`, `created_at`) VALUES ('Yurem', 'Barton', '@mycompayny.com', '7b72301a558c0bf6cba1a2', '2022-08-17 23:59:59');
INSERT INTO `GTUProjectManagement`.`User` (`first_name`, `last_name`, `email`, `password`, `created_at`) VALUES ('Rayne', 'Foster', '@mycompayny.com', '7b72301a558c0bf6cba1a2', '2022-08-17 23:59:59');
INSERT INTO `GTUProjectManagement`.`User` (`first_name`, `last_name`, `email`, `password`, `created_at`) VALUES ('Chace', 'Lee', '@mycompayny.com', '7b72301a558c0bf6cba1a2', '2022-08-17 23:59:59');
INSERT INTO `GTUProjectManagement`.`User` (`first_name`, `last_name`, `email`, `password`, `created_at`) VALUES ('Kierra', 'Howell', '@mycompayny.com', '7b72301a558c0bf6cba1a2', '2022-08-17 23:59:59');
INSERT INTO `GTUProjectManagement`.`User` (`first_name`, `last_name`, `email`, `password`, `created_at`) VALUES ('Chandler', 'Reeves', '@mycompayny.com', '7b72301a558c0bf6cba1a2', '2022-08-17 23:59:59');
INSERT INTO `GTUProjectManagement`.`User` (`first_name`, `last_name`, `email`, `password`, `created_at`) VALUES ('Salvatore', 'Booth', '@mycompayny.com', '7b72301a558c0bf6cba1a2', '2022-08-17 23:59:59');
INSERT INTO `GTUProjectManagement`.`User` (`first_name`, `last_name`, `email`, `password`, `created_at`) VALUES ('Dangelo', 'Johns', '@mycompayny.com', '7b72301a558c0bf6cba1a2', '2022-08-17 23:59:59');
INSERT INTO `GTUProjectManagement`.`User` (`first_name`, `last_name`, `email`, `password`, `created_at`) VALUES ('Madeline', 'Thornton', '@mycompayny.com', '7b72301a558c0bf6cba1a2', '2022-08-17 23:59:59');
INSERT INTO `GTUProjectManagement`.`User` (`first_name`, `last_name`, `email`, `password`, `created_at`) VALUES ('Paisley', 'Sexton', '@mycompayny.com', '7b72301a558c0bf6cba1a2', '2022-08-17 23:59:59');
INSERT INTO `GTUProjectManagement`.`User` (`first_name`, `last_name`, `email`, `password`, `created_at`) VALUES ('Makena', 'Mendoza', '@mycompayny.com', '7b72301a558c0bf6cba1a2', '2022-08-17 23:59:59');
INSERT INTO `GTUProjectManagement`.`User` (`first_name`, `last_name`, `email`, `password`, `created_at`) VALUES ('Alissa', 'Holder', '@mycompayny.com', '7b72301a558c0bf6cba1a2', '2022-08-17 23:59:59');
INSERT INTO `GTUProjectManagement`.`User` (`first_name`, `last_name`, `email`, `password`, `created_at`) VALUES ('Dominik', 'Boyd', '@mycompayny.com', '7b72301a558c0bf6cba1a2', '2022-08-17 23:59:59');

INSERT INTO `GTUProjectManagement`.`TMRoles` (`name`, `description`) VALUES ('business analyst', 'Define, analyze, and manage technical and business requirements throughout the whole project cycle.');
INSERT INTO `GTUProjectManagement`.`TMRoles` (`name`, `description`) VALUES ('product owner', 'Establish effective communication between the client/end users and the development team.');
INSERT INTO `GTUProjectManagement`.`TMRoles` (`name`, `description`) VALUES ('project manager', 'Develop a project plan.');
INSERT INTO `GTUProjectManagement`.`TMRoles` (`name`, `description`) VALUES ('team lead', 'Guide the team development towards successful project delivery.');
INSERT INTO `GTUProjectManagement`.`TMRoles` (`name`, `description`) VALUES ('software architect', 'Define the technical and functional architecture of the overall system.');
INSERT INTO `GTUProjectManagement`.`TMRoles` (`name`, `description`) VALUES ('developers', 'Develop the features laid out in the Sprint.');
INSERT INTO `GTUProjectManagement`.`TMRoles` (`name`, `description`) VALUES ('qa team', 'Evaluate the execution of processes and production of deliverables according to the defined software process.');
INSERT INTO `GTUProjectManagement`.`TMRoles` (`name`, `description`) VALUES ('ux/ui designers', 'Analyze functional requirements intended for the users.');
INSERT INTO `GTUProjectManagement`.`TMRoles` (`name`, `description`) VALUES ('testers', 'Understand what the system’s requirements are in order to create and review adequate test cases.');
INSERT INTO `GTUProjectManagement`.`TMRoles` (`name`, `description`) VALUES ('master', 'Be a facilitator to serve the team to make sure that they follow Agile values and implement the correct methodology');

INSERT INTO `GTUProjectManagement`.`Team` (`name`, `created_at`) VALUES ('Rocket Team', '1000-01-01 00:00:00');
INSERT INTO `GTUProjectManagement`.`Team` (`name`, `created_at`) VALUES ('No Lucks Given', '2022-06-17 00:00:00');
INSERT INTO `GTUProjectManagement`.`Team` (`name`, `created_at`) VALUES ('We’re On Mute', '2022-06-17 00:00:00');
INSERT INTO `GTUProjectManagement`.`Team` (`name`, `created_at`) VALUES ('Insert Team Name Here', '2022-06-17 00:00:00');
INSERT INTO `GTUProjectManagement`.`Team` (`name`, `created_at`) VALUES ('Our Team Name is Invisible', '2022-06-17 00:00:00');
INSERT INTO `GTUProjectManagement`.`Team` (`name`, `created_at`) VALUES ('We Tried', '2022-06-17 00:00:00');

INSERT INTO `GTUProjectManagement`.`Task` (`name`, `description`, `created_at`, `planned_end_date`, `priority_id`, `task_class_id`, `project_id`) VALUES ('7 Pictures ', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', '2022-06-18 01:11:19', '2022-09-18 23:59:55', '4', '1', '1');
INSERT INTO `GTUProjectManagement`.`Task` (`name`, `description`, `created_at`, `planned_end_date`, `priority_id`, `task_class_id`, `project_id`) VALUES ('How to Increase ', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', '2022-06-18 01:11:19', '2022-09-18 23:59:55', '4', '5', '1');
INSERT INTO `GTUProjectManagement`.`Task` (`name`, `description`, `created_at`, `planned_end_date`, `priority_id`, `task_class_id`, `project_id`) VALUES ('21 Myths', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', '2022-06-18 01:11:19', '2022-09-18 23:59:55', '1', '5', '1');
INSERT INTO `GTUProjectManagement`.`Task` (`name`, `description`, `created_at`, `planned_end_date`, `priority_id`, `task_class_id`, `project_id`) VALUES ('Introducing Anonymous', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', '2022-06-18 01:11:19', '2022-09-18 23:59:55', '1', '1', '2');
INSERT INTO `GTUProjectManagement`.`Task` (`name`, `description`, `created_at`, `planned_end_date`, `priority_id`, `task_class_id`, `project_id`) VALUES ('Shape Shifter', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', '2022-06-18 01:11:19', '2022-09-18 23:59:55', '2', '2', '2');
INSERT INTO `GTUProjectManagement`.`Task` (`name`, `description`, `created_at`, `planned_end_date`, `priority_id`, `task_class_id`, `project_id`) VALUES ('Can Giraffes Dance', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', '2022-06-18 01:11:19', '2022-09-18 23:59:55', '3', '2', '2');
INSERT INTO `GTUProjectManagement`.`Task` (`name`, `description`, `created_at`, `planned_end_date`, `priority_id`, `task_class_id`, `project_id`) VALUES ('Giraffes Are', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', '2022-06-18 01:11:19', '2022-09-18 23:59:55', '7', '2', '3');
INSERT INTO `GTUProjectManagement`.`Task` (`name`, `description`, `created_at`, `planned_end_date`, `priority_id`, `task_class_id`, `project_id`) VALUES ('20 Tights ', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', '2022-06-18 01:11:19', '2022-09-18 23:59:55', '3', '3', '3');
INSERT INTO `GTUProjectManagement`.`Task` (`name`, `description`, `created_at`, `planned_end_date`, `priority_id`, `task_class_id`, `project_id`) VALUES ('From Zero to Shape Shifter', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', '2022-06-18 01:11:19', '2022-09-18 23:59:55', '4', '4', '3');
INSERT INTO `GTUProjectManagement`.`Task` (`name`, `description`, `created_at`, `planned_end_date`, `priority_id`, `task_class_id`, `project_id`) VALUES ('YouTube Videos', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', '2022-06-18 01:11:19', '2022-09-18 23:59:55', '5', '5', '5');
INSERT INTO `GTUProjectManagement`.`Task` (`name`, `description`, `created_at`, `planned_end_date`, `priority_id`, `task_class_id`, `project_id`) VALUES ('10 Awesome', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', '2022-06-18 01:11:19', '2022-09-18 23:59:55', '7', '1', '5');

INSERT INTO `GTUProjectManagement`.`TeamProject` (`project_id`, `team_id`) VALUES ('1', '2');
INSERT INTO `GTUProjectManagement`.`TeamProject` (`project_id`, `team_id`) VALUES ('2', '2');
INSERT INTO `GTUProjectManagement`.`TeamProject` (`project_id`, `team_id`) VALUES ('2', '3');
INSERT INTO `GTUProjectManagement`.`TeamProject` (`project_id`, `team_id`) VALUES ('2', '4');
INSERT INTO `GTUProjectManagement`.`TeamProject` (`project_id`, `team_id`) VALUES ('3', '2');
INSERT INTO `GTUProjectManagement`.`TeamProject` (`project_id`, `team_id`) VALUES ('4', '2');
INSERT INTO `GTUProjectManagement`.`TeamProject` (`project_id`, `team_id`) VALUES ('4', '5');
INSERT INTO `GTUProjectManagement`.`TeamProject` (`project_id`, `team_id`) VALUES ('4', '6');
INSERT INTO `GTUProjectManagement`.`TeamProject` (`project_id`, `team_id`) VALUES ('5', '5');
INSERT INTO `GTUProjectManagement`.`TeamProject` (`project_id`, `team_id`) VALUES ('6', '6');

INSERT INTO `GTUProjectManagement`.`UserTask` (`task_id`, `user_id`) VALUES ('1', '1');
INSERT INTO `GTUProjectManagement`.`UserTask` (`task_id`, `user_id`) VALUES ('1', '2');
INSERT INTO `GTUProjectManagement`.`UserTask` (`task_id`, `user_id`) VALUES ('2', '3');
INSERT INTO `GTUProjectManagement`.`UserTask` (`task_id`, `user_id`) VALUES ('3', '4');
INSERT INTO `GTUProjectManagement`.`UserTask` (`task_id`, `user_id`) VALUES ('4', '4');
INSERT INTO `GTUProjectManagement`.`UserTask` (`task_id`, `user_id`) VALUES ('5', '4');
INSERT INTO `GTUProjectManagement`.`UserTask` (`task_id`, `user_id`) VALUES ('6', '5');
INSERT INTO `GTUProjectManagement`.`UserTask` (`task_id`, `user_id`) VALUES ('7', '6');
INSERT INTO `GTUProjectManagement`.`UserTask` (`task_id`, `user_id`) VALUES ('8', '7');
INSERT INTO `GTUProjectManagement`.`UserTask` (`task_id`, `user_id`) VALUES ('9', '8');
INSERT INTO `GTUProjectManagement`.`UserTask` (`task_id`, `user_id`) VALUES ('10', '8');
INSERT INTO `GTUProjectManagement`.`UserTask` (`task_id`, `user_id`) VALUES ('10', '8');
INSERT INTO `GTUProjectManagement`.`UserTask` (`task_id`, `user_id`) VALUES ('10', '9');
INSERT INTO `GTUProjectManagement`.`UserTask` (`task_id`, `user_id`) VALUES ('11', '10');
INSERT INTO `GTUProjectManagement`.`UserTask` (`task_id`, `user_id`) VALUES ('11', '11');

INSERT INTO `GTUProjectManagement`.`TeamUserRole` (`user_id`, `team_id`, `role_id`) VALUES ('1', '1', '1');
INSERT INTO `GTUProjectManagement`.`TeamUserRole` (`user_id`, `team_id`, `role_id`) VALUES ('2', '2', '2');
INSERT INTO `GTUProjectManagement`.`TeamUserRole` (`user_id`, `team_id`, `role_id`) VALUES ('3', '3', '3');
INSERT INTO `GTUProjectManagement`.`TeamUserRole` (`user_id`, `team_id`, `role_id`) VALUES ('4', '4', '4');
INSERT INTO `GTUProjectManagement`.`TeamUserRole` (`user_id`, `team_id`, `role_id`) VALUES ('5', '5', '5');
INSERT INTO `GTUProjectManagement`.`TeamUserRole` (`user_id`, `team_id`, `role_id`) VALUES ('6', '6', '6');
INSERT INTO `GTUProjectManagement`.`TeamUserRole` (`user_id`, `team_id`, `role_id`) VALUES ('7', '1', '7');
INSERT INTO `GTUProjectManagement`.`TeamUserRole` (`user_id`, `team_id`, `role_id`) VALUES ('8', '2', '8');
INSERT INTO `GTUProjectManagement`.`TeamUserRole` (`user_id`, `team_id`, `role_id`) VALUES ('9', '3', '9');
INSERT INTO `GTUProjectManagement`.`TeamUserRole` (`user_id`, `team_id`, `role_id`) VALUES ('10', '4', '10');
INSERT INTO `GTUProjectManagement`.`TeamUserRole` (`user_id`, `team_id`, `role_id`) VALUES ('11', '5', '1');
INSERT INTO `GTUProjectManagement`.`TeamUserRole` (`user_id`, `team_id`, `role_id`) VALUES ('12', '6', '2');
INSERT INTO `GTUProjectManagement`.`TeamUserRole` (`user_id`, `team_id`, `role_id`) VALUES ('1', '2', '3');
INSERT INTO `GTUProjectManagement`.`TeamUserRole` (`user_id`, `team_id`, `role_id`) VALUES ('2', '3', '4');
INSERT INTO `GTUProjectManagement`.`TeamUserRole` (`user_id`, `team_id`, `role_id`) VALUES ('2', '4', '5');
INSERT INTO `GTUProjectManagement`.`TeamUserRole` (`user_id`, `team_id`, `role_id`) VALUES ('2', '5', '6');
